services:
  # Servicio para PostgreSQL
  postgres:
    image: postgres:18
    container_name: bdd_postgres_db
    environment:
      POSTGRES_DB: bdd_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql


volumes:
    db_data:
